---

- name: Install AWS SSM agent
  yum:
    name: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
    disable_gpg_check: yes
    state: present

- name: Start the AWS SSM agent service
  service:
    name: amazon-ssm-agent
    state: started
    enabled: yes
